export type Role =
  | 'LANDLORD'
  | 'TENANT'
  | 'ADMINISTRATOR'
  | 'COORDINATOR'
  | 'TEACHER'
  | 'EDUCATIONAL_RESPONSIBLE'
  | 'FINANCIAL_RESPONSIBLE'
  | 'STUDENT'

export const Role = {
  LANDLORD: 'LANDLORD' as Role,
  TENANT: 'TENANT' as Role,
  ADMINISTRATOR: 'ADMINISTRATOR' as Role,
  COORDINATOR: 'COORDINATOR' as Role,
  TEACHER: 'TEACHER' as Role,
  EDUCATIONAL_RESPONSIBLE: 'EDUCATIONAL_RESPONSIBLE' as Role,
  FINANCIAL_RESPONSIBLE: 'FINANCIAL_RESPONSIBLE' as Role,
  STUDENT: 'STUDENT' as Role,
}
